exclude-ifaces:
  - lo*
  - bond*
  - wg*
exclude-networks:
  [ 192.168.2.0/24 ]
threads: 32
restart-interval: 10
db-uri: "ispcsroute:PtK97QaDYqHhxVhq@tcp(10.2.1.20)/billing-dev"
file-store-name: "store.txt"
