exclude-ifaces:
  - lo*
  - bond*
  - wg*
exclude-networks: [10.3.*]
threads: 8
restart-interval: 180
dsn: "ispcsroute:pass@tcp(10.2.1.20)/billing?parseTime=True&loc=Europe%2FKiev&charset=utf8"
file-store-name: "store.txt"
store: "mysql"
