exclude-ifaces:
  - lo*
  - bond*
  - wg*
exclude-networks:
  [ 192.3.* ]
threads: 32
restart-interval: 60
db-uri: "ispcsroute:PtK97QaDYqHhxVhq@tcp(10.2.1.20)/billing-dev"
file-store-name: "store.txt"
